import { ChartColumn, History, Home, ListOrdered, Package, PackagePlus, Settings, ShoppingBag, UserCheck, UserPlus, Users } from "lucide-react";

import ProfileImage from "@/assets/profile-image.png";
import ProductImage from "@/assets/product-image.jpg";
import PrinterImg from "../assets/printerImg.jpg";

export const navbarLinks = [
  {
    title: "Dashboard",
    links: [
      {
        label: "Dashboard",
        icon: Home,
        path: "/dashboard",
      },
      {
        label: "Print Queue",
        icon: ListOrdered,
        path: "/print-queue",
      },
      {
        label: "Print History",
        icon: History,
        path: "/prints-history",
      },
    ],
  },
  {
    title: "User Admin",
    links: [
      {
        label: "Users",
        icon: Users,
        path: "/users",
      },
      {
        label: "Add User",
        icon: UserPlus,
        path: "/add-user",
      },
    ],
  },
  {
    title: "Printer Config",
    links: [
      {
        label: "Printers",
        icon: Package,
        path: "/printer-config",
      },
      {
        label: "New printer",
        icon: PackagePlus,
        path: "/new-printer",
      },
      {
        label: "Inventory",
        icon: ShoppingBag,
        path: "/inventory",
      },
    ],
  },
  {
    title: "Settings",
    links: [
      {
        label: "Settings",
        icon: Settings,
        path: "/settings",
      },
    ],
  },
];

export const overviewData = [
  {
    name: "Jan",
    total: 800,
  },
  {
    name: "Feb",
    total: 1500,
  },
  {
    name: "Mar",
    total: 1000,
  },
  {
    name: "Apr",
    total: 2000,
  },
  {
    name: "May",
    total: 1800,
  },
  {
    name: "Jun",
    total: 3200,
  },
  {
    name: "Jul",
    total: 2000,
  },
  {
    name: "Aug",
    total: 500,
  },
  {
    name: "Sep",
    total: 5500,
  },
  {
    name: "Oct",
    total: 4000,
  },
  {
    name: "Nov",
    total: 1500,
  },
  {
    name: "Dec",
    total: 2500,
  },
];

export const recentSalesData = [
  {
    id: 1,
    name: "Olivia Martin",
    email: "olivia.martin@email.com",
    image: ProfileImage,
    total: 1500,
  },
  {
    id: 2,
    name: "James Smith",
    email: "james.smith@email.com",
    image: ProfileImage,
    total: 2000,
  },
  {
    id: 3,
    name: "Sophia Brown",
    email: "sophia.brown@email.com",
    image: ProfileImage,
    total: 4000,
  },
  {
    id: 4,
    name: "Noah Wilson",
    email: "noah.wilson@email.com",
    image: ProfileImage,
    total: 3000,
  },
  {
    id: 5,
    name: "Emma Jones",
    email: "emma.jones@email.com",
    image: ProfileImage,
    total: 2500,
  },
  {
    id: 6,
    name: "William Taylor",
    email: "william.taylor@email.com",
    image: ProfileImage,
    total: 4500,
  },
  {
    id: 7,
    name: "Isabella Johnson",
    email: "isabella.johnson@email.com",
    image: ProfileImage,
    total: 5300,
  },
];

export const topProducts = [
  {
    number: 1,
    name: "Wireless Headphones",
    image: ProductImage,
    description: "High-quality noise-canceling wireless headphones.",
    price: 99.99,
    status: "In Stock",
    rating: 4.5,
  },
  {
    number: 2,
    name: "Smartphone",
    image: ProductImage,
    description: "Latest 5G smartphone with excellent camera features.",
    price: 799.99,
    status: "In Stock",
    rating: 4.7,
  },
  {
    number: 3,
    name: "Gaming Laptop",
    image: ProductImage,
    description: "Powerful gaming laptop with high-end graphics.",
    price: 1299.99,
    status: "In Stock",
    rating: 4.8,
  },
  {
    number: 4,
    name: "Smartwatch",
    image: ProductImage,
    description: "Stylish smartwatch with fitness tracking features.",
    price: 199.99,
    status: "Out of Stock",
    rating: 4.4,
  },
  {
    number: 5,
    name: "Bluetooth Speaker",
    image: ProductImage,
    description: "Portable Bluetooth speaker with deep bass sound.",
    price: 59.99,
    status: "In Stock",
    rating: 4.3,
  },
  {
    number: 6,
    name: "4K Monitor",
    image: ProductImage,
    description: "Ultra HD 4K monitor with stunning color accuracy.",
    price: 399.99,
    status: "In Stock",
    rating: 4.6,
  },
  {
    number: 7,
    name: "Mechanical Keyboard",
    image: ProductImage,
    description: "Mechanical keyboard with customizable RGB lighting.",
    price: 89.99,
    status: "In Stock",
    rating: 4.7,
  },
  {
    number: 8,
    name: "Wireless Mouse",
    image: ProductImage,
    description: "Ergonomic wireless mouse with precision tracking.",
    price: 49.99,
    status: "In Stock",
    rating: 4.5,
  },
  {
    number: 9,
    name: "Action Camera",
    image: ProductImage,
    description: "Waterproof action camera with 4K video recording.",
    price: 249.99,
    status: "In Stock",
    rating: 4.8,
  },
  {
    number: 10,
    name: "External Hard Drive",
    image: ProductImage,
    description: "Portable 2TB external hard drive for data storage.",
    price: 79.99,
    status: "Out of Stock",
    rating: 4.5,
  },
];

export const printQueue = [
  {
    number: 1,
    printName: "SculptFlow ",
    orderNumber: "ref1",
    userName: "Jon Doe",
    printStatus: "Ready",
    duration: 7,
    printer: "Tshwane",
    category: "Resin",
    priority: "High",
  },
  {
    number: 2,
    printName: "Voxel Vision",
    orderNumber: "ref2",
    userName: "Jon Doe",
    printStatus: "Ready",
    duration: 4,
    printer: "Tshwane",
    category: "Resin",
    priority: "High",
  },
  {
    number: 3,
    printName: "Filament Muse",
    orderNumber: "ref3",
    userName: "Jon Doe",
    printStatus: "Ready",
    duration: 2,
    printer: "Tshwane",
    category: "Plastic",
    priority: "High",
  },
  {
    number: 4,
    printName: "PrintCanvas ",
    orderNumber: "ref4",
    userName: "Jon Doe",
    printStatus: "Ready",
    duration: 1,
    printer: "Tshwane",
    category: "Plastic",
    priority: "High",
  },
  {
    number: 5,
    printName: "Layered Elegance",
    orderNumber: "ref5",
    userName: "Jon Doe",
    printStatus: "Ready",
    duration: 18,
    printer: "Tshwane",
    category: "Resin",
    priority: "High",
  },
  {
    number: 6,
    printName: "Form & Flow",
    orderNumber: "ref6",
    userName: "Jon Doe",
    printStatus: "Ready",
    duration: 12,
    printer: "Tshwane",
    category: "Plastic",
    priority: "High",
  },
  {
    number: 7,
    printName: "Filigree Forge",
    orderNumber: "ref7",
    userName: "Jon Doe",
    printStatus: "Ready",
    duration: 3,
    printer: "Tshwane",
    category: "Plastic",
    priority: "High",
  },
  {
    number: 8,
    printName: "AetherPrint",
    orderNumber: "ref8",
    userName: "Jon Doe",
    printStatus: "Ready",
    duration: 6,
    printer: "Tshwane",
    category: "Metal",
    priority: "High",
  },
  {
    number: 9,
    printName: "Parametric Pulse",
    orderNumber: "ref9",
    userName: "Jon Doe",
    printStatus: "Ready",
    duration: 7,
    printer: "Tshwane",
    category: "Metal",
    priority: "High",
  },
  {
    number: 10,
    printName: "NeoSculpt",
    orderNumber: "ref10",
    userName: "Jon Doe",
    printStatus: "Ready",
    duration: 4,
    printer: "Tshwane",
    category: "Resin",
    priority: "High",
  },
];

export const printJobCategories = [
  {
    title: "Filament-Based",
    key: "Plastic",
  },
  {
    title: "Resin-Based",
    key: "Resin",
  },
  {
    title: "Metal-Based",
    key: "Metal",
  },
];

export const printHistory = [
  {
    printName: "SculptFlow ",
    userName: "Jon Doe",
    printStatus: "Complete",
    duration: 0,
    printer: "Tshwane",
  },
  {
    printName: "Voxel Vision",
    userName: "Jon Doe",
    printStatus: "Complete",
    duration: 0,
    printer: "Tshwane",
  },
  {
    printName: "Filament Muse",
    userName: "Jon Doe",
    printStatus: "Complete",
    duration: 0,
    printer: "Tshwane",
  },
  {
    printName: "PrintCanvas ",
    userName: "Jon Doe",
    printStatus: "Error",
    duration: 0,
    printer: "Tshwane",
  },
  {
    printName: "Layered Elegance",
    userName: "Jon Doe",
    printStatus: "In progress",
    duration: 3,
    printer: "Tshwane",
  },
  {
    printName: "Form & Flow",
    userName: "Jon Doe",
    printStatus: "Complete",
    duration: 5,
    printer: "Tshwane",
  },
  {
    printName: "Filigree Forge",
    userName: "Jon Doe",
    printStatus: "In progress",
    duration: 6,
    printer: "Tshwane",
  },
  {
    printName: "AetherPrint",
    userName: "Jon Doe",
    printStatus: "In progress",
    duration: 9,
    printer: "Tshwane",
  },
  {
    printName: "Parametric Pulse",
    userName: "Jon Doe",
    printStatus: "Complete",
    duration: 7,
    printer: "Tshwane",
  },
  {
    printName: "NeoSculpt",
    userName: "Jon Doe",
    printStatus: "Error",
    duration: 0,
    printer: "Tshwane",
  },
];

export const usersList = [
  {
    regNumber: 1,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Verified",
  },
  {
    regNumber: 2,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Verified",
  },
  {
    regNumber: 3,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Verified",
  },
  {
    regNumber: 4,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Verified",
  },
  {
    regNumber: 5,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Verified",
  },
  {
    regNumber: 6,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Verified",
  },
  {
    regNumber: 7,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Revoked",
  },
  {
    regNumber: 8,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Not Verified",
  },
  {
    regNumber: 9,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Verified",
  },
  {
    regNumber: 10,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Verified",
  },
  {
    regNumber: 11,
    image: ProfileImage,
    userName: {
      firstName: "Jon",
      lastName: "Doe",
    },
    email: "test@mail.com",
    address: {
      streetName: "123 Havanna Str",
      suburb: "Springs",
      postalCode: 1980,
      city: "Johannesburg",
      country: "South Africa",
    },
    registeredAt: "11 Oct 2024",
    status: "Not Verified",
  },
];

export const printers = [
  {
    image: PrinterImg,
    number: 1,
    printerName: "Tshwane",
    status: "Available",
    progress: "N/A",
    printerType: "Filament-Based(FDM/FFF)",
    duration: "N/A",
  },
  {
    image: PrinterImg,
    number: 2,
    printerName: "Tshwane",
    status: "Available",
    progress: "N/A",
    printerType: "Filament-Based(FDM/FFF)",
    duration: "N/A",
  },
  {
    image: PrinterImg,
    number: 3,
    printerName: "Tshwane",
    status: "Error",
    progress: "N/A",
    printerType: "Resin-Based",
    duration: "N/A",
  },
  {
    image: PrinterImg,
    number: 4,
    printerName: "Tshwane",
    status: "Busy",
    progress: "32%",
    printerType: "Resin-Based",
    duration: 2,
  },
  {
    image: PrinterImg,
    number: 5,
    printerName: "Tshwane",
    status: "Busy",
    progress: "76%",
    printerType: "DLP(Digital Light Processing)",
    duration: 3,
  },
  {
    image: PrinterImg,
    number: 6,
    printerName: "Tshwane",
    status: "Busy",
    progress: "85%",
    printerType: "DLP(Digital Light Processing)",
    duration: 2,
  },
  {
    image: PrinterImg,
    number: 7,
    printerName: "Tshwane",
    status: "Error",
    progress: "N/A",
    printerType: "Powder-Based",
    duration: "N/A",
  },
  {
    image: PrinterImg,
    number: 8,
    printerName: "Tshwane",
    status: "Busy",
    progress: "63%",
    printerType: "Powder-Based",
    duration: 2,
  },
  {
    image: PrinterImg,
    number: 9,
    printerName: "Tshwane",
    status: "Busy",
    progress: "77%",
    printerType: "Powder-Based",
    duration: 3,
  },
  {
    image: PrinterImg,
    number: 10,
    printerName: "Tshwane",
    status: "Busy",
    progress: "85%",
    printerType: "Powder-Based",
    duration: 2,
  },
  {
    image: PrinterImg,
    number: 11,
    printerName: "Tshwane",
    status: "Busy",
    progress: "24%",
    printerType: "Powder-Based",
    duration: 16,
  },
  {
    image: PrinterImg,
    number: 12,
    printerName: "Tshwane",
    status: "Busy",
    progress: "98%",
    printerType: "Powder-Based",
    duration: 1,
  },
];
